# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-24 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'корзина', 'verbose_name_plural': 'Корзины'},
        ),
    ]
