# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-21 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20180721_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('title',), 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
