# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-24 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20180725_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=49.99, max_digits=20, null=True),
        ),
    ]
